name: CI
on: push

jobs:
  check-style:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: python -m pip install --upgrade pip pycodestyle

      - name: CI
        run: pycodestyle --first *.py

      - name: Test with pytest  # This is new!
        run: |
          python3 -m unittest youtube_testfile.py